import { useEffect, useMemo, useRef } from 'react';
import { Button } from '@/components/ui/button';
import { Square } from 'lucide-react';
import { useGeometry } from '@/context/GeometryContext';
import { normalizePlanarPolygon } from '@/lib/geometry/planeGeometry';

export function AddPlaneTool() {
  const { state, addPlane, clearSelection } = useGeometry();
  const pointMap = useMemo(
    () => new Map(state.geometry?.points.map((point) => [point.id, point]) ?? []),
    [state.geometry?.points],
  );
  // Resolve by actual geometry membership. IDs generated by AI do not
  // necessarily start with `line_` or `plane_`.
  const selectedPoints = useMemo(
    () => state.selectedIds.filter((id) => pointMap.has(id)),
    [pointMap, state.selectedIds],
  );
  const validPolygon = useMemo(() => {
    if (selectedPoints.length < 3) return null;
    return normalizePlanarPolygon(selectedPoints.map((id) => pointMap.get(id)!));
  }, [pointMap, selectedPoints]);
  const prevSelectedRef = useRef<string[]>([]);

  useEffect(() => {
    const previous = prevSelectedRef.current;

    // Clicking the first point again removes it from selectedIds and closes the
    // loop. Keep the selection when validation fails so the user can correct it.
    if (previous.length >= 3 && selectedPoints.length === previous.length - 1) {
      if (previous[0] && !selectedPoints.includes(previous[0])) {
        if (addPlane(previous)) {
          clearSelection();
          prevSelectedRef.current = [];
        } else {
          prevSelectedRef.current = selectedPoints;
        }
        return;
      }
    }

    prevSelectedRef.current = selectedPoints;
  }, [selectedPoints, addPlane, clearSelection]);

  const handleAdd = () => {
    if (!validPolygon) return;
    if (addPlane(selectedPoints)) clearSelection();
  };

  return (
    <div className="space-y-3 text-center text-xs text-muted-foreground pb-1">
      <p>
        Chọn ít nhất 3 điểm đồng phẳng. Thứ tự điểm sẽ được tự sắp xếp để mặt
        không bị bắt chéo.
      </p>

      {selectedPoints.length > 0 && (
        <p className="text-primary font-medium text-[10px] animate-pulse">
          Đã chọn: {selectedPoints.join(', ')}
          {selectedPoints.length < 3
            ? ` (cần thêm ${3 - selectedPoints.length} điểm)`
            : validPolygon
              ? ' (sẵn sàng)'
              : ' (các điểm không đồng phẳng hoặc bị suy biến)'}
        </p>
      )}

      <Button
        size="sm"
        className="w-full h-7 text-xs"
        onClick={handleAdd}
        disabled={!validPolygon}
      >
        <Square className="w-3 h-3 mr-1" /> Tạo mặt phẳng
      </Button>
    </div>
  );
}
